
include: package:lint/analysis_options.yaml

# custom lint rules

linter:
  rules:
    prefer_const_constructors : true
    prefer_const_constructors_in_immutables : true
    prefer_const_declarations : true
    prefer_const_literals_to_create_immutables : true
    unnecessary_lambdas : true
    recursive_getters: true
    prefer_final_locals: true
    prefer_single_quotes: false
    prefer_void_to_null: true
    void_checks: true
    await_only_futures : true
    use_full_hex_values_for_flutter_colors: true

# make the type system stronger!
# see https://dart.dev/guides/language/analysis-options
analyzer:
  exclude:
     - build/**
      # workaround for https://github.com/dart-lang/sdk/issues/42910
     - example/**
  language:
    strict-inference: true
    strict-raw-types: true
  strong-mode:
    # never implicitly cast types down
    implicit-casts: false
    # never implicitly use dynamic when a type cannot be inferred, require type annotations in this case
    implicit-dynamic: false
  errors:
    missing_required_param: warning
    # treat missing returns as a warning (not a hint)
    missing_return: warning
    # allow having TODOs in the code
    todo: warning
    unused_import: warning
    uri_has_not_been_generated: error
    dead_code: warning