name: diffutil_sliverlist
description: A SliverList that implicitly animates changes using diffutil.dart.
version: 0.5.0
homepage: https://github.com/knaeckeKami/diffutil_sliverlist

environment:
  sdk: '>=2.12.0-29.10.beta <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  diffutil_dart: ^2.0.0-nullsafety.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: any
