name: diffutil_sliverlist
description: A SliverList that implicitly animates changes using diffutil.dart.
version: 0.5.1
homepage: https://github.com/knaeckeKami/diffutil_sliverlist

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  diffutil_dart: '>=2.0.0 <4.0.0'
  flutter:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.8.2
